import { expect, it } from "vitest";

import {
  isAsciiDxf,
  isAsciiHpgl,
  probeFxgExport,
  probeGplExport,
  probeWebpExport,
} from "../../src/capabilities/export-probe.js";
import { inspectDxf } from "../../src/export/dxf.js";
import { inspectHpgl } from "../../src/export/hpgl.js";
import { inspectGpl } from "../../src/export/gpl.js";
import { inspectFxg } from "../../src/export/fxg.js";

it("recognizes a structural ASCII DXF even when it has a leading comment", () => {
  expect(
    isAsciiDxf(
      Buffer.from(
        "999\nGenerated by Inkscape\n0\nSECTION\n2\nHEADER\n0\nENDSEC\n0\nEOF\n",
        "ascii",
      ),
    ),
  ).toBe(true);
});

it("rejects incomplete and binary DXF-like outputs", () => {
  expect(isAsciiDxf(Buffer.from("0\nSECTION\n2\nHEADER\n", "ascii"))).toBe(
    false,
  );
  expect(isAsciiDxf(Buffer.from([0, 0x41, 0xff]))).toBe(false);
});

it("reports stable DXF metadata only for structurally complete output", () => {
  expect(
    inspectDxf(Buffer.from("0\nSECTION\n2\nENTITIES\n0\nENDSEC\n0\nEOF\n")),
  ).toEqual({ byteLength: 36, sectionCount: 1 });
  expect(() => inspectDxf(Buffer.from("0\nEOF\n"))).toThrow("SECTION");
});

it("recognizes only bounded ASCII HPGL command streams", () => {
  expect(isAsciiHpgl(Buffer.from("IN;PU0,0;PD1,1;", "ascii"))).toBe(true);
  expect(isAsciiHpgl(Buffer.from("PU0,0;PD1,1;", "ascii"))).toBe(false);
  expect(isAsciiHpgl(Buffer.from([0x49, 0x4e, 0, 0x3b]))).toBe(false);
  expect(inspectHpgl(Buffer.from("IN;PU0,0;PD1,1;"))).toEqual({
    byteLength: 15,
    penCommandCount: 2,
  });
});

it("validates a bounded GIMP palette and rejects malformed palette output", () => {
  expect(
    inspectGpl(
      Buffer.from(
        "GIMP Palette\nName: Inkscape document\nColumns: 4\n#\n17 34 51 blue\n",
        "utf8",
      ),
    ),
  ).toEqual({ byteLength: 64, colorCount: 1, name: "Inkscape document" });
  expect(() =>
    inspectGpl(Buffer.from("GIMP Palette\nName: Missing colors\nColumns: 4\n")),
  ).toThrow("no palette colors");
  expect(() =>
    inspectGpl(
      Buffer.from("GIMP Palette\nName: Invalid\nColumns: 33\n1 2 3\n"),
    ),
  ).toThrow("invalid palette columns");
});

it("validates FXG XML without allowing active declarations", () => {
  expect(
    inspectFxg(
      Buffer.from(
        '<Graphic version="2.0" xmlns="http://ns.adobe.com/fxg/2008"><Path data="M 0 0 L 1 1"/></Graphic>',
      ),
    ),
  ).toEqual({ byteLength: 96, version: "2.0" });
  expect(() =>
    inspectFxg(
      Buffer.from('<!DOCTYPE fxg><Graphic version="2.0"><Path/></Graphic>'),
    ),
  ).toThrow("active XML declarations");
  expect(() =>
    inspectFxg(Buffer.from('<Graphic version="3.0"><Path/></Graphic>')),
  ).toThrow("unsupported version");
});

it("reports a missing FXG artifact without leaking its scratch path", async () => {
  const result = await probeFxgExport(
    {
      run: async () => ({
        durationMs: 1,
        exitCode: 0,
        pid: 1,
        signal: null,
        stderr: Buffer.alloc(0),
        stderrTruncated: false,
        stdout: Buffer.alloc(0),
        stdoutTruncated: false,
        terminationReason: "completed" as const,
      }),
    },
    process.execPath,
    {
      maxStderrBytes: 1024,
      maxStdoutBytes: 1024,
      processTimeoutMs: 1_000,
      scratchRoot: "auto",
    },
  );
  expect(result).toEqual({
    available: false,
    reason: "FXG output is missing or unreadable",
  });
});

it("reports a missing GPL artifact without leaking its scratch path", async () => {
  const result = await probeGplExport(
    {
      run: async () => ({
        durationMs: 1,
        exitCode: 0,
        pid: 1,
        signal: null,
        stderr: Buffer.alloc(0),
        stderrTruncated: false,
        stdout: Buffer.alloc(0),
        stdoutTruncated: false,
        terminationReason: "completed" as const,
      }),
    },
    process.execPath,
    {
      maxStderrBytes: 1024,
      maxStdoutBytes: 1024,
      processTimeoutMs: 1_000,
      scratchRoot: "auto",
    },
  );
  expect(result).toEqual({
    available: false,
    reason: "GPL output is missing or unreadable",
  });
});

it("reports a missing WebP artifact without leaking its scratch path", async () => {
  const result = await probeWebpExport(
    {
      run: async () => ({
        durationMs: 1,
        exitCode: 0,
        pid: 1,
        signal: null,
        stderr: Buffer.alloc(0),
        stderrTruncated: false,
        stdout: Buffer.alloc(0),
        stdoutTruncated: false,
        terminationReason: "completed" as const,
      }),
    },
    process.execPath,
    {
      maxRasterMegapixels: 1,
      maxStderrBytes: 1024,
      maxStdoutBytes: 1024,
      processTimeoutMs: 1_000,
      scratchRoot: "auto",
    },
  );
  expect(result).toEqual({
    available: false,
    reason: "WebP output is missing or unreadable",
  });
});
