import { expect, it } from "vitest";

import { isAsciiDxf } from "../../src/capabilities/export-probe.js";
import { inspectDxf } from "../../src/export/dxf.js";

it("recognizes a structural ASCII DXF even when it has a leading comment", () => {
  expect(
    isAsciiDxf(
      Buffer.from(
        "999\nGenerated by Inkscape\n0\nSECTION\n2\nHEADER\n0\nENDSEC\n0\nEOF\n",
        "ascii",
      ),
    ),
  ).toBe(true);
});

it("rejects incomplete and binary DXF-like outputs", () => {
  expect(isAsciiDxf(Buffer.from("0\nSECTION\n2\nHEADER\n", "ascii"))).toBe(
    false,
  );
  expect(isAsciiDxf(Buffer.from([0, 0x41, 0xff]))).toBe(false);
});

it("reports stable DXF metadata only for structurally complete output", () => {
  expect(
    inspectDxf(Buffer.from("0\nSECTION\n2\nENTITIES\n0\nENDSEC\n0\nEOF\n")),
  ).toEqual({ byteLength: 36, sectionCount: 1 });
  expect(() => inspectDxf(Buffer.from("0\nEOF\n"))).toThrow("SECTION");
});
