import { expect, it } from "vitest";

import {
  isAsciiDxf,
  isAsciiHpgl,
  probeWebpExport,
} from "../../src/capabilities/export-probe.js";
import { inspectDxf } from "../../src/export/dxf.js";
import { inspectHpgl } from "../../src/export/hpgl.js";

it("recognizes a structural ASCII DXF even when it has a leading comment", () => {
  expect(
    isAsciiDxf(
      Buffer.from(
        "999\nGenerated by Inkscape\n0\nSECTION\n2\nHEADER\n0\nENDSEC\n0\nEOF\n",
        "ascii",
      ),
    ),
  ).toBe(true);
});

it("rejects incomplete and binary DXF-like outputs", () => {
  expect(isAsciiDxf(Buffer.from("0\nSECTION\n2\nHEADER\n", "ascii"))).toBe(
    false,
  );
  expect(isAsciiDxf(Buffer.from([0, 0x41, 0xff]))).toBe(false);
});

it("reports stable DXF metadata only for structurally complete output", () => {
  expect(
    inspectDxf(Buffer.from("0\nSECTION\n2\nENTITIES\n0\nENDSEC\n0\nEOF\n")),
  ).toEqual({ byteLength: 36, sectionCount: 1 });
  expect(() => inspectDxf(Buffer.from("0\nEOF\n"))).toThrow("SECTION");
});

it("recognizes only bounded ASCII HPGL command streams", () => {
  expect(isAsciiHpgl(Buffer.from("IN;PU0,0;PD1,1;", "ascii"))).toBe(true);
  expect(isAsciiHpgl(Buffer.from("PU0,0;PD1,1;", "ascii"))).toBe(false);
  expect(isAsciiHpgl(Buffer.from([0x49, 0x4e, 0, 0x3b]))).toBe(false);
  expect(inspectHpgl(Buffer.from("IN;PU0,0;PD1,1;"))).toEqual({
    byteLength: 15,
    penCommandCount: 2,
  });
});

it("reports a missing WebP artifact without leaking its scratch path", async () => {
  const result = await probeWebpExport(
    {
      run: async () => ({
        durationMs: 1,
        exitCode: 0,
        pid: 1,
        signal: null,
        stderr: Buffer.alloc(0),
        stderrTruncated: false,
        stdout: Buffer.alloc(0),
        stdoutTruncated: false,
        terminationReason: "completed" as const,
      }),
    },
    process.execPath,
    {
      maxRasterMegapixels: 1,
      maxStderrBytes: 1024,
      maxStdoutBytes: 1024,
      processTimeoutMs: 1_000,
      scratchRoot: "auto",
    },
  );
  expect(result).toEqual({
    available: false,
    reason: "WebP output is missing or unreadable",
  });
});
